---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
        - name: code-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: code-server-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8443
  selector:
    app: code-server

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-server-ingress
spec:
  rules:
    - host: code-server.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: code-server-service
                port:
                  number: 8443

---
