# values.yaml
---
nginx:
  domain: "coder.dev"

developerCount: 2

developerNames:
  - chuck
  - bob

individualStorageSize: 5Gi
sharedStorageSize: 5Gi

image:
  repository: chuckspeed/vscode
  tag: "1.0"
