authentik:
  secret_key: "3ZoiSwDnk5mOFxqsswOxq7ue1gZ1wmeYio95lCTD2Cs="
  postgresql:
    host: authentik-postgresql.code-dev.svc.cluster.local
    port: 5432
    password: "3wWrKZwxs5gPy5vzDzrUpCNdPKnfo8xT"
  redis:
    host: authentik-redis-master.code-dev.svc.cluster.local
    password: "2wq2HSwC1tTTXP5RBAswcmk9UXIaxcmI"
postgresql:
  auth:
    password: "3wWrKZwxs5gPy5vzDzrUpCNdPKnfo8xT"

redis:
  auth:
    enabled: true
  password: "2wq2HSwC1tTTXP5RBAswcmk9UXIaxcmI"

  server:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
  worker:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi

  ingress:
    enabled: false

  service:
    type: ClusterIP
    port: 80

server:
  ingress:
    enabled: false

postgresql:
  enabled: true
  persistence:
    enabled: true
    size: 8Gi

redis:
  enabled: true
  master:
    persistence:
      enabled: true
      size: 8Gi